channels:
- conda-forge
dependencies:
- coverage
- lammps =2024.08.29=*_mpi_mpich_*
- mpich =4.3.2
- numpy =2.4.0
- mpi4py =4.1.1
- executorlib =1.7.3
- ase =3.27.0
- scipy =1.16.3
- hatchling
- hatch-vcs
